version: '3'

services:

  booking-rest-service:
    build: .
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=abc
      - POSTGRES_USER=abc
      - POSTGRES_DB=roombooking
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: